### ISSUE TITLE
Orbiter stops on map show when viewing orange line route

### ISSUE THREAD

**Issue by NichollsC** [CanterburyRegionalCouncil/MetroInfoMaps#38]
unlike other routes when I view orange line on chrome the orbiter bus stops across city show as well as the orange line bus stops
![viewing orange line](https://cloud.githubusercontent.com/assets/6656769/8535314/c554deb8-2498-11e5-996a-1848b0c6da97.JPG)

**Comment by SamDrummond** [comment]
I can replicate this issue. This issue exists in the current production [site](http://www.metroinfo.co.nz/map). 

I will investigate to see where this issues is occuring and what needs to be done to solve it.

**Comment by SamDrummond** [comment]
Claire & Ryan, this appears to be a data issue. All the bus stops for both the Orange Line and the Orbiter are tagged as 'O' - rather than the Orbiter stops being tagged with 'Or'.

The query for the Orange Line brings back results from both the orange line and the orbiter:
http://gis.ecan.govt.nz/arcgis/rest/services/Public/Bus_Routes/MapServer/1/query?where=%28RouteNos+like+%27%25%7CO%27+or+RouteNos+like+%27%7CO%25%27+or+RouteNos+like+%27O%7C%25%27+or+RouteNos+like+%27%25%7CO%7C%25%27+or+RouteNos+%3D+%27O%27%29+AND+ProjectID%3D%27CHCMETRO%27&text=&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=4326&spatialRel=esriSpatialRelIntersects&relationParam=&outFields=*&returnGeometry=true&maxAllowableOffset=&geometryPrecision=6&outSR=4326&returnIdsOnly=false&returnCountOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&gdbVersion=&returnDistinctValues=false&returnTrueCurves=false&resultOffset=&resultRecordCount=&f=html

The query for the Orbitor brings back nothing:

http://gis.ecan.govt.nz/arcgis/rest/services/Public/Bus_Routes/MapServer/1/query?where=%28RouteNos+like+%27%25%7COr%27+or+RouteNos+like+%27%7COr%25%27+or+RouteNos+like+%27Or%7C%25%27+or+RouteNos+like+%27%25%7COr%7C%25%27+or+RouteNos+%3D+%27Or%27%29+AND+ProjectID%3D%27CHCMETRO%27&text=&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=4326&spatialRel=esriSpatialRelIntersects&relationParam=&outFields=*&returnGeometry=true&maxAllowableOffset=&geometryPrecision=6&outSR=4326&returnIdsOnly=false&returnCountOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&gdbVersion=&returnDistinctValues=false&returnTrueCurves=false&resultOffset=&resultRecordCount=&f=html

**Comment by pogglethelesser** [comment]
I'll get Hamish to have a look at the bus stops and sort out the issue.  It appears there was a problem when the stops data was last updated the other day.

**Comment by SamDrummond** [comment]
@NichollsC this appears resolved is it okay if we close this off?
